package com.king.practices.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.king.practices.mvp.model.entity.Gank;
import com.king.practices.mvp.model.entity.GankHistoryDate;

import com.king.practices.greendao.GankDao;
import com.king.practices.greendao.GankHistoryDateDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gankDaoConfig;
    private final DaoConfig gankHistoryDateDaoConfig;

    private final GankDao gankDao;
    private final GankHistoryDateDao gankHistoryDateDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gankDaoConfig = daoConfigMap.get(GankDao.class).clone();
        gankDaoConfig.initIdentityScope(type);

        gankHistoryDateDaoConfig = daoConfigMap.get(GankHistoryDateDao.class).clone();
        gankHistoryDateDaoConfig.initIdentityScope(type);

        gankDao = new GankDao(gankDaoConfig, this);
        gankHistoryDateDao = new GankHistoryDateDao(gankHistoryDateDaoConfig, this);

        registerDao(Gank.class, gankDao);
        registerDao(GankHistoryDate.class, gankHistoryDateDao);
    }
    
    public void clear() {
        gankDaoConfig.clearIdentityScope();
        gankHistoryDateDaoConfig.clearIdentityScope();
    }

    public GankDao getGankDao() {
        return gankDao;
    }

    public GankHistoryDateDao getGankHistoryDateDao() {
        return gankHistoryDateDao;
    }

}
